version: '2.4'
services:
    webapp:
        image: httpd:2.4-apache
        build:
            context: webapp/
            dockerfile: Dockerfile
        ports:
        - "80:80"
        - "443:443"
    webapi:
        image: alpine:3.9
